services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./.docker-compose/dev/start.sh
    ports:
      - 3005:3000
    volumes:
      - .:/home/node/app
    environment:
      - TZ=America/Sao_Paulo

  pgsql:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - 5445:5432
    volumes:
      - 'pgsql_database:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s

volumes:
  pgsql_database:
    driver: local
  mongo_database:
    driver: local
